---
- name: create a home for the toolbox
  file:
    path: /opt/freeton-toolbox
    state: directory
    owner: "{{ ansible_user }}"

- name: create a place for logs
  file:
    path: /var/log/freeton-toolbox
    state: directory
    owner: "{{ ansible_user }}"
